[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "cyclozarin"
name = "DealCancel"
description = "A mod for Content Warning that allows you cancel sponsorship if something went wrong"
websiteUrl = "https://github.com/cyclozarin/DealCancel"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Hamunii-AutoHookGenPatcher = "1.0.2"

[build]
icon = "icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/cyclozarin.contentwarning.DealCancel.dll"
target = "/BepInEx/plugins/DealCancel/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "mods", "bepinex", "vanillacomp", "serverside" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
